[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "juss>=0.0.0",
    "justfile>=0.0.1a0",
    "mamushi>=0.0.8",
    "moccasin>=0.4.2",
    "snekmate>=0.1.2",
]
